### ISSUE TITLE
Header cutoff

### ISSUE THREAD

**Issue by Riking27** [Timwi/Kyudosudoku#4]
Header is cut off in my browser. Chrome 94.0.4606.81
Only appears to happen inside a puzzle.
![image](https://user-images.githubusercontent.com/77776657/138575181-7a5e3cb9-0bcf-4ac0-8f84-57d808c9294b.png)

**Comment by Riking27** [comment]
Issue is fixed when an account is made. Has something to do with the "not logged in" element shoving the header off the page, surely.

**Comment by Timwi** [comment]
I believe this was fixed at some point.
