### ISSUE TITLE
Puzzle #300 is wrongly filtered

### ISSUE THREAD

**Issue by Prism019** [Timwi/Kyudosudoku#7]
For some reason, puzzle \#300 (which is marked as having no constraints and actually has no constraints) is filtered out when selecting to exclude the Arrow constraint.

Before:
![image](https://user-images.githubusercontent.com/7096478/176787519-70e9100c-3c6d-45cc-8150-6c57474681cc.png)
After:
![image](https://user-images.githubusercontent.com/7096478/176787540-7e4af85c-5896-4e09-9bb8-203dd7c203c9.png)

There are probably more examples of this happening, but I don't particularly feel like spending a bunch of time testing out all sorts of different constraint filters and flipping through every page to see if something is missing x.x

**Comment by Timwi** [comment]
Thanks, fixed!
